name: "[Feature] 새로운 기능 제안"
description: "프로젝트에 추가할 새로운 기능을 제안해주세요."
title: "[Feature] " # 이슈 기본 제목 형식
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: "추가하고 싶은 기능에 대한 상세 설명을 작성해주세요."
      placeholder: "자세히 적을수록 좋아요!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: "할 일을 체크박스 형태로 작성해주세요."
      placeholder: "- [ ] 기능1\n- [ ] 기능2"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: "관련 문서나 이미지, 링크가 있다면 작성해주세요."
      placeholder: "예: https://example.com"
